# Import modułów i pakietów

In [14]:
import numpy as np
from keras import Sequential
from keras.layers import Dense
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

# Wczytywanie danych z pliku csv

In [15]:
df = pd.read_csv('wyniki_cech.csv', sep=',')
data = df.to_numpy()
X = data[:,:-1].astype('float')
y = data[:,-1]

# Wstępne przetwarzanie danych

In [20]:
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(y)
# binary encode
onehot_encoder = OneHotEncoder(sparse_output=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)

X_train, X_test, y_train, y_test = train_test_split(X, onehot_encoded, test_size=0.3)

# Tworzenie modelu sieci neuronowej

In [21]:
model = Sequential()
model.add(Dense(10, input_dim=72, activation='sigmoid'))
model.add(Dense(3, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
model.summary()

C:\Users\wilcz\anaconda3\envs\lab4\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                     │ (None, 10)                  │             730 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_11 (Dense)                     │ (None, 3)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 763 (2.98 KB)

 Trainable params: 763 (2.98 KB)

 Non-trainable params: 0 (0.00 B)

# Uczenie sieci

In [24]:
model.fit(X_train, y_train, epochs=100, batch_size=10, shuffle=True)

Epoch 1/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8930 - loss: 0.7987 
Epoch 2/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step - accuracy: 0.8389 - loss: 0.7854
Epoch 3/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step - accuracy: 0.8099 - loss: 0.8155
Epoch 4/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step - accuracy: 0.8372 - loss: 0.7780
Epoch 5/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8677 - loss: 0.7524 
Epoch 6/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step - accuracy: 0.8683 - loss: 0.7648
Epoch 7/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step - accuracy: 0.8045 - loss: 0.8026
Epoch 8/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8446 - loss: 0.7709 
Epoch 9/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step - accuracy: 0.8351 - loss: 0.7747
Epoch 10/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step - accuracy: 0.8683 - loss: 0.7976
Epoch 11/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step - accuracy: 0.8436 - loss: 0.7691
Epoch 12/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1

# Testowanie sieci

In [25]:
y_pred = model.predict(X_test)
y_pred_int = np.argmax(y_pred, axis=1)
y_test_int = np.argmax(y_test, axis=1)
cm = confusion_matrix(y_test_int, y_pred_int)
print(cm)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step  
[[25  0  2]
 [ 0 21  0]
 [ 1  0 20]]
